name: Maven Package

on:
  push:
    branches:
      - "master"
#  release:
#    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: redefantasy
          settings-path: ${{ github.workspace }}  # Local onde está o settings.xml

      - name: Build with Maven
        run: mvn -B package --file pom.xml
        
      - name: Check Maven Publish Credentials
        run: |
          if [ -z "$GITHUB_MAVEN_PUBLISH_USER" ] || [ -z "$GITHUB_MAVEN_PUBLISH_PASSWORD" ]; then
            echo "Credenciais não definidas!"
            exit 1
          else
            echo "As credenciais foram definidas."
          fi
        shell: bash
  
      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml

    env:
      MAVEN_PUBLISH_USER: ${{ secrets.MAVEN_PUBLISH_USER }}
      MAVEN_PUBLISH_PASSWORD: ${{ secrets.MAVEN_PUBLISH_PASSWORD }}