name: Maven Package

on:
  push:
    branches:
      - "master"
#  release:
#    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: redefantasy
          settings-path: ${{ github.workspace }}

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: List files in workspace
        run: ls -la $GITHUB_WORKSPACE

      - name: Copy settings.xml to Maven home
        run: cp $GITHUB_WORKSPACE/settings.xml ~/.m2/settings.xml

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml

    env:
      MAVEN_PUBLISH_USER: ${{ secrets.MAVEN_PUBLISH_USER }}
      MAVEN_PUBLISH_PASSWORD: ${{ secrets.MAVEN_PUBLISH_PASSWORD }}